### PR TITLE
Daniel resource contd

### PR DESCRIPTION
**Pull request by dkrasner**
### Main Points ###

This PR introduces a number of significant changes and additions:

* the `Resource` part and view, for interacting with remote REST API's
* system plugins for extending functionality and resources of ST
* creating the `wants-*` property (in particular the `wants-move` for parts where we want to be able to handle moving the views around without having the editing halo on)
    * removal of the old, and largely unused, `events` property and framework
* add/delete property grammar, semantics, messages and command handlers

and a bunch of tests + example....

#### Resources and Plugins ####

Plugins are just JS objects which live in the `plugins` directory, exported as the [plugins object](https://github.com/dkrasner/Simpletalk/pull/30/files#diff-d62a52cece4605a3c927a193f9c634ccb8fa8107b9e412e3596a23813f6259cd) and [loaded](https://github.com/dkrasner/Simpletalk/pull/30/files#diff-27807be337857d016752d52609f4312048ef006984f0d2e108676823ffe892f6R117) when the System starts up. There are no assumptions about what these plugins are. There is also no "high-level" way to add them at the moment, with say a ST `install plugin "XYZ"` type of grammar, but we can deal with that later. 

Resource parts (and views) are ST objects. The view is a simple wrapper around an icon and name (in the future I imagine we'll allow to change the icon programmatically). The **only** contract between a `Resource` part and some resource plugin is that the latter has `get` function. 

Take a look at the [test example](https://github.com/dkrasner/Simpletalk/pull/30/files#diff-04af93238d065e69031c9f85a13b0815c23322fe3e7f9140f98a099899ee1f25) and the [merriam one](https://github.com/dkrasner/Simpletalk/pull/30/files#diff-d0e88ddf49fab8806edc9f9b38d265a6bfe90305f500e28eb3ed5355a7871466) and the  [Resource part](https://github.com/dkrasner/Simpletalk/pull/30/files#diff-b67b626f0c2e4dcaf331a48617236063da049b5b2e91eeedbd8544df1e938e3f). The result of the `get [args]` command is placed in the `response` part property which can then be referenced as needed in ST. (In the `resource-example.html` I `tell resource "Test" to get` and subsequently `tell field "Result" to set "text" to the "result" of resource "Tests"` and so on)

The `get`, as in `tell resource "My Resource" to get [args]` basically allows to offload whatever resource specific complexity to the plugin. REST API, DB interfaces etc are all different and this allows you to calibrate what you want ST to see and deal with. Whatever arguments come along with `get` are simply passed to the plugin and dealt with there. 

This works ok. There is a `resourceReady` property which is either `notReady` `fetching` or `ready` and the view subscribes to the change setting the border color from red to yellow to green respectively. 

Dealing with fetching various fields from the API is a bit awkward, but that can be fixed with better plugins and potentially being able to use `expressions` with properties. For example `the [expression] of resource "My Resource"` where the expression is a local variable or a property that indicates what field you are looking for at the moment etc. 

Regardless I think there is enough there to start putting together something demonstrable, which depends on a REST API. With some playing around it will be more clear what the design ought to be. 

#### Wants-* ####

It became clear that simply passing along DOM events to the models is not that useful. DOM events don't really correspond to the events one 'naturally' imagines. For example, if you want to move something in the browser with a mouse you need to use a combination of `mousedown` `mousemove` and `mouseup` or something similar. So simply passing these along as messages directly responding to events firing in the DOM was not a great idea. 

Hence, I've introduced a `wants-move` part property which does what you imagine and all the DOM events stuff is handled under the hood. So now you can do something like

```
add area to current card
tell first area to set "wants-move" to true
```

and then move it around. I imagine adding  a bunch of `wants-*` properties like `wants-hover` `wants-drag` and so on. 

Finally..

#### add / delete properties

We can now do things like:
```
add property "NewProp"
set "NewProp" to "cool"
delete property "NewProp"
```
(similarly `add property "NewProperty" to button 10 in third card`  etc)

In the future I think all the add, delete and set of properties should take expressions and not just string literals for names. This way you can use either local "variables" or other properties to specify new ones. This would be useful when dealing with async resources like REST API's as discussed above.

I **did not** remove global variables, but assume with these changes they will become obsolete. 

#### Tests ####

I've added and updated a bunch of tests.

There is a `resource-example.html` which has a basic test resource on the first card and a Merriam one on the second. Note: you don't need to click on the "setup" buttons since the respective resource parts are serialized, but you can see how they are made; and, for the Merriam one to work the API has to be up and running which as of writing it is. 

Conflicts have been resolved.

### CODE REVIEW

**Comment by ApproximateIdentity** [comment]
@dkrasner I haven't had a chance to look into this in detail, but I did push a tiny bugfix here:

https://github.com/dkrasner/Simpletalk/pull/30/commits/5be759138540488210d682f89339e8a18b2fa69c

Looks like the filename got messed up somehow.

(If I'm missing something here feel free the revert the commit, but I couldn't build it without this change...)

**Comment by darth-cheney** [comment]
### Resources ###
The design choices here make sense to me. As you say, we will likely want some "chunking-like" way to dig into response objects but that is part of a bigger issue.
  
One thing I would still like here is to have a message automatically sent to the Resource part whenever a response or error comes back from the request. This way we don't have to do stepping to constantly check for the resource state and response status. I think it would make the scripts of such things a little more readable as a result.
  
We could do the same for the actual resource state changes as well, automatically sending a message of some sort whenever the status changes (beyond the normal `propertyChanged` message, so we don't catch everything) so that we can update other Parts when this happens. This is not as important though.
  
Do we think there is a potential problem with having the resource plugins be singleton objects? If I have two Merriam resources in my stack, presumably they are sharing the same instance of the resource plugin and therefore their cached responses could overwrite each other, correct?
  
### Wants- ###
This is the right approach for sure. We need to be extra careful with these mouse events, since we also use them for halo interaction etc. For example, opening a halo on a button and clicking the mouse down to start moving it is "activating" the button. Also, if I set `wants-move` on a button to true, I can move it as expected, but now it also clicks every time I finish my move. Maybe that's what one would expect -- hard to say. The wants-move example seems to work well otherwise. We will figure out the rest as we go.
  
### Custom Properties ###
Custom properties are not being serialized and/or deserialized correctly. If I add one to some part, save a snapshot, then reload it, there is an error. This is one reason why I think user-specified properties should somehow be separate from the built-in ones, either by being instances of some particular subclass of `BasicProperty` or by being stored in a separate set of properties. We always want to be able to tell  if a give property is a "custom" one, I think. 

Do we want to check for the existence of a given property before adding a custom one ([here](https://github.com/dkrasner/Simpletalk/blob/daniel-resource-contd/js/objects/System.js#L382)), and throw some custom error if the prop already exists?
  
> In the future I think all the add, delete and set of properties should take expressions and not just string literals for names. This way you can use either local "variables" or other properties to specify new ones. This would be useful when dealing with async resources like REST API's as discussed above.
  
This is something I've been thinking about for a while, because it is very clunky to determine or understand when to use quotations or not. This has long been an issue for me. For example, take the most recent resource script:
```simpletalk
tell field "Result" to set "text" to the "result" of resource "Tests"
```
If I'm a novice user I would have next to no idea why some things are in quotes and some things aren't.
  
And, in fact, we are not making full use of our control over the grammar in this regard. There is no reason that:
```simpletalk
set "any-property-name" to 4
```
cannot _also_ be written as:
```simpletalk
set any-property-name to 4
```
because the `set` command is built into the grammar and interpreter.
  
So what I propose is that things like `set` should be updated to take two things: a valid token without spaces (ie `any-property-name`) or a string literal (ie, `"any-property-name"`). The string literal option allows us to dynamically compose the names, using variables and string concatenation if needed. The token version allows us to write quick, readable script without a bunch of confusing and unnecessary quotations.
  
In the end, the resource example above could be expressed as:
```simpletalk
tell field "Result" to set text to the result of resource "Tests"
```
  
If you all agree, I can open an issue about this

**Comment by dkrasner** [comment]
@darth-cheney ok I've reworked custom properties, in view of the issues above. 


Here is the basic breakdown. 

there is now a [CustomProperty](https://github.com/dkrasner/Simpletalk/blob/daniel-resource-contd/js/objects/properties/PartProperties.js#L93) class. Technically this could really be a `DynamicProperty` but it was a lot easier for me to reason and debug with this little object and some helper methods. 

It's sole purpose is to store stuff in the `customProp._value` object. In particular it can add, delete and find objects there (maybe it's better that `customProp._value` is an array to more closely match `PartProperties` work but it's a minor point at the moment). There is really no assumption about what this k-v store holds; it can be a basic prop, dynamic or something else entirely down the line. But for the purpose of our v1 custom props, it stores `BasicProperty` objects. 

Since all setting, getting, removing in `PartProperties` depends on just one method [findPropertyNamed()](https://github.com/dkrasner/Simpletalk/blob/daniel-resource-contd/js/objects/properties/PartProperties.js#L223) this is all I changed. The assumption is that if you don't find a ST 'native' prop then go look and see if it's custom. After then setting it is just the same as setting any property (since you are now working with a `BasicProperty` that just happens to be 'custom', so writing property change handler for custom props in ST works like before). 

System [won't allow](https://github.com/dkrasner/Simpletalk/blob/daniel-resource-contd/js/objects/System.js#L383) you to add properties with names that already exists, which prevents you overwriting 'native' props or even custom ones but that's not so important. 

On de-serialization the value of `custom-property` is just an object that contains data (k-v's) for the underlying `BasicProperty` objects (just like for all properties). So I've added a [branch for this](https://github.com/dkrasner/Simpletalk/blob/daniel-resource-contd/js/objects/parts/Part.js#L624) in the `setPropsFromDeserializer` which then takes all this props data and makes new `BasicProps` to be set as the value of `custom-properties`. There is clearly a smarter way to do this but I think it works fine an is pretty easy to debug. 

I've written some tests for the properties. 

In the future i can imagine we might different types of custom props people will add, and this can allow us to keep things sane.

**Comment by darth-cheney** [comment]
@dkrasner I think this is a good first pass at the custom properties stuff. I can think of several things we _might_ want to add to this capability down the road should we find we want them (default values etc).
  
There is one thing that might be useful upfront, but which might actually warrant a separate issue: checking for the presence of a given property using `there is a`. Since we can add and remove properties programmatically it's useful to be able to check for the existence of one on a given part. I don't have a strong opinion about whether or not that work should be in this PR specifically since there is so much here already.
  
Aside from that I say merge it in and let's keep in rolling

**Comment by dkrasner** [comment]
> The design choices here make sense to me. As you say, we will likely want some "chunking-like" way to dig into response objects but that is part of a bigger issue.
> 
> One thing I would still like here is to have a message automatically sent to the Resource part whenever a response or error comes back from the request. This way we don't have to do stepping to constantly check for the resource state and response status. I think it would make the scripts of such things a little more readable as a result.
> 
> We could do the same for the actual resource state changes as well, automatically sending a message of some sort whenever the status changes (beyond the normal `propertyChanged` message, so we don't catch everything) so that we can update other Parts when this happens. This is not as important though.

I have resource now send a `responded` or `errored` command message to itself, on which you can script. This is how the "merriam" example is currently written and I think it works fine (much better than the previous version). 

> 
> Do we think there is a potential problem with having the resource plugins be singleton objects? If I have two Merriam resources in my stack, presumably they are sharing the same instance of the resource plugin and therefore their cached responses could overwrite each other, correct?
yes i think this is a problem but lets kick it to another PR. I've opened an issue #38 about it and we just have to be mindful for the moment. 

> ### Wants-
> 
> This is the right approach for sure. We need to be extra careful with these mouse events, since we also use them for halo interaction etc. For example, opening a halo on a button and clicking the mouse down to start moving it is "activating" the button. Also, if I set `wants-move` on a button to true, I can move it as expected, but now it also clicks every time I finish my move. Maybe that's what one would expect -- hard to say. The wants-move example seems to work well otherwise. We will figure out the rest as we go.

i played around with different version of this and didn't really like any of them. Maybe we don't allow the button to be moved, maybe we allow it and expect click to happen. Either way lets see what `wants-move` really does for us and go from there... 

> I can think of several things we might want to add to this capability down the road should we find we want them (default values etc).
yeah we can think of the grammar for that later, it would be easy to add under the hood.


> There is one thing that might be useful upfront, but which might actually warrant a separate issue: checking for the presence of a given property using there is a. Since we can add and remove properties programmatically it's useful to be able to check for the existence of one on a given part. I don't have a strong opinion about whether or not that work should be in this PR specifically since there is so much here already.

yeah this is right, Issue #39 opened

**Pull request merged**
