### PR TITLE
New Editor

### PR DESCRIPTION
**Pull request by darth-cheney**
## What ##
This PR implements a new comprehensive Part Editor that slides out from the left side of the window when editing a Part.
  
The goal of the new editor is to provide an accessible, one stop shop for modifying properties and viewing information about a given Part.
  
It replaces the previous st-editor and st-button-editor components.

## Description and How to Use ##
The Editor can be opened on any Part by sending it the `openEditor` message or by clicking the gear icon in a Halo.
  
It is currently composed of four "tabs" that reveal corresponding panes:
#### _Properties_ Pane ####
The _Properties_ pane gives authors a list of property names and inputs/togglers they can use to modify the values. A filter field at the top of the pane can be used to filter by property name. This pane does not list any custom properties.
  

  
Properties do not update live -- instead, "accept" and "reject" buttons will appear alongside any input to confirm that the author wants the change. Rejecting will reset the input back to the property value. The exception to this is checkboxes: these *do* update live.
  
#### _Custom_ Pane ####
The _Custom_ pane is where authors can view, modify, and create custom properties. It is the same as the _Properties_ pane (filtering and all) with the exception of the ability to add a new property.
  

  
#### _Messenger_ Pane ####
The _Messenger_ pane provides authors with a single place to send arbitrary messages to the Part that is being edited. This is useful when you are creating stacks and don't want to have to create an ephemeral field just to run a doIt command.
  

  
#### _Subparts_ Pane ####
The _Subparts_ pane is divided into three sections.
  
The first is a __row of buttons__ for adding subparts to the current part. It is limited to only those kinds of parts that the current part accepts.
  
The second is a __description of ancestors and their locations__. It will provide buttons that link to the ancestor Stack and/or Card (if relevant) and the Part's current Owner. The link buttons, when clicked, will open the editor on those respective parts. Additionally, we provide Simpletalk objectspecifier strings that describe the location of each of these parts. Clicking the location copies that string to the clipboard, so that it can be pasted into scripts etc.
  
The third section is a __list of the Part's subpart items__. Each provides basic information about the subpart. Clicking the item will open the editor on that subpart.
  

## Implementation ##
  
The new Editor is not written in Simpletalk, nor is it made from Simpletalk Parts. Instead, we have made prodigious use of custom webcomponents, all of which can be found in [`js/objects/views/editors`](https://github.com/dkrasner/Simpletalk/tree/eric-comp-editor/js/objects/views/editors). These components all have a `render()` method that takes a Part instance. This is how an editor is "opened on" a given Part.
  
The editor element is registered as `st-editor` and is added to the DOM by the System at load time. 
  
You can directly toggle this element via the `.open()` and `.close()` methods, as well as checking the `.isOpen` property.
  
## Future Work ##
The Editor should be usable, but there are obvious things to do in the near future. 
  
For one, we should have some kind of type annotation on our built-in System properties, so that we know if they should be numerical, textual, or boolean. This would allow us to use components like range sliders and more in the Properties pane.
  
Also, a future PR implementing a contextual click (right click menu) will complement this Editor well and should kind of be a priority.

### CODE REVIEW

**Comment by dkrasner** [comment]
that's really nice...

will play around some more

**Comment by dkrasner** [comment]
This is really nice!

one question about object specifiers: should these be relative or deterministic? At the moment they are the former, but it's unclear to me that's what you want.IE if you are looking for _that_ part as opposed to a part in that place, then it should be an id - what do you think?

**Comment by darth-cheney** [comment]
> one question about object specifiers: should these be relative or deterministic? At the moment they are the former, but it's unclear to me that's what you want.IE if you are looking for that part as opposed to a part in that place, then it should be an id - what do you think?
  
One thing I've been thinking about is how we want to "lead" authors by our interfaces and examples. Thomas and I had discussed trying to limit the habit of referring to things by ID in scripts as much as possible. Having the location available to copy and paste is one small way of doing so. That said, I'm not opposed to also displaying the ID and making a copy button for it in the same way.
  
> should we also add the location of the part in question so it can be copied in the same way?
  
Yeah definitely. Question is: should it go a the header of the menu (where the Part type and name is displayed) or just in the subparts pane?

**Comment by dkrasner** [comment]
> Yeah definitely. Question is: should it go a the header of the menu (where the Part type and name is displayed) or just in the subparts pane?

i think in the subparts pane is natural, that's where all the references are

**Comment by dkrasner** [comment]
> > one question about object specifiers: should these be relative or deterministic? At the moment they are the former, but it's unclear to me that's what you want.IE if you are looking for that part as opposed to a part in that place, then it should be an id - what do you think?
> 
> One thing I've been thinking about is how we want to "lead" authors by our interfaces and examples. Thomas and I had discussed trying to limit the habit of referring to things by ID in scripts as much as possible. Having the location available to copy and paste is one small way of doing so. That said, I'm not opposed to also displaying the ID and making a copy button for it in the same way.

you could always offer both: _relative_ and _deterministic_

There is really no way to know what someone is going to do with a part, and that will determine how the object specifier should act. So it's important that people get the difference and understand when to use one over the other.

**Comment by darth-cheney** [comment]
@dkrasner I've pushed a commit that implements both a new set of buttons for the part being edited (ie, My location is...) and adds an ID button to all of the ancestor references in the subparts pane. This should take care of the two comments you posted above. Let me know if there's anything else.

**Comment by dkrasner** [comment]
@darth-cheney that makes sense

couple of issues and bugs:

I think the current wording "i am located.... and my id is.." is too long but that's debatable. However when we flip over to uuids that will be much longer and i think a bit nasty/intimidating looking

copying the location copies a proper object specifier string (`first button of first card` etc) 

But copying the id just copies the number. The intention here is that you will do something with these copied strings, mainly use them in a script, so they should both be usable in a script. 

I would simply forgo even displaying the id (and potentially the location string - debatable), and simply have two copy icons "copy location" "copy with id" 

you could use location icons like [this](https://tabler-icons.io/i/map-pin), [this](https://tabler-icons.io/i/pin), or [this](https://tabler-icons.io/i/location) and an [id icon](https://tabler-icons.io/i/id)

there is an underlying assumption that all numeric properties are integers, so things like `background-transparency` up.down prop editor errors increase and decrease these by +1/-1, which does nothing (unless you hit 0 or 1). Maybe you can match on `*-transparency` and have those be [0, 1] with .1 increments. 

I know we talked about the color-wheel for `*-color` props but that can be left for later since it's a bit of work. 


Pinning can make the object disappear out of the editor focus view. Not sure what we can do about that at the moment... 

I would allow for `return` button to accept a new prop value. You can tab through the props which is nice and it would be great to allow you to tab, type to edit and then return to accept. 
 

bugs:
image

looks like there is an assumption that the ancestor has to be a card, which is not the case for parts on a stack.

also this error is throw when i add  a button and click on the editor halo-icon
image


I am sure these were already there and i didn't notice them earlier... would have been more productive if i had

**Comment by darth-cheney** [comment]
> I think the current wording "i am located.... and my id is.." is too long but that's debatable. However when we flip over to uuids that will be much longer and i think a bit nasty/intimidating looking
> I would simply forgo even displaying the id (and potentially the location string - debatable), and simply have two copy icons "copy location" "copy with id"
  
I've kept the location strings because I think they are useful to know, but I've gone ahead and removed the id from being displayed in the copy id button. Now it just copies the id. If we want it to put `part id <id>` into the clipboard we can change that too.
  
> there is an underlying assumption that all numeric properties are integers, so things like background-transparency up.down prop editor errors increase and decrease these by +1/-1, which does nothing (unless you hit 0 or 1). Maybe you can match on *-transparency and have those be [0, 1] with .1 increments.
  
I've gone ahead and made the `-transparency` property editor inputs render themselves as range types (sliders) with a min of 0, a max of 1 and a step of 0.05. Also, I've made these update immediately on input unlike the numeric/text fields.
  
> I would allow for return button to accept a new prop value. You can tab through the props which is nice and it would be great to allow you to tab, type to edit and then return to accept.
  
Done
  
> looks like there is an assumption that the ancestor has to be a card, which is not the case for parts on a stack.
> also this error is throw when i add a button and click on the editor halo-icon
  
These were actually the same bug, which I've now fixed
  
> that's not that useful. Maybe it should close the editor maybe it should center the script field. I also can't toggle the script editor which is what i expect within the editor itself
  
The Editor will now open the scriptEditor (at 100@100 now) and close itself. This is a better flow for sure.
  
> I wonder if the best thing to do is simply edit the script in the messenger console?, i.e. there are two modes: send message to part and edit the script (but this is more work)
  
We discussed that and decided we wanted to keep the script editor as a pure Simpletalk composition, which I think is the right move. I too was tempted to add a basic script editor into the Editor panes but after our conversation decided against it.

**Comment by dkrasner** [comment]
> > I think the current wording "i am located.... and my id is.." is too long but that's debatable. However when we flip over to uuids that will be much longer and i think a bit nasty/intimidating looking
> > I would simply forgo even displaying the id (and potentially the location string - debatable), and simply have two copy icons "copy location" "copy with id"
> 
> I've kept the location strings because I think they are useful to know, but I've gone ahead and removed the id from being displayed in the copy id button. Now it just copies the id. If we want it to put `part id <id>` into the clipboard we can change that too.

i say we want `part id <id>` in the string
> 
> > there is an underlying assumption that all numeric properties are integers, so things like background-transparency up.down prop editor errors increase and decrease these by +1/-1, which does nothing (unless you hit 0 or 1). Maybe you can match on *-transparency and have those be [0, 1] with .1 increments.
> 
> I've gone ahead and made the `-transparency` property editor inputs render themselves as range types (sliders) with a min of 0, a max of 1 and a step of 0.05. Also, I've made these update immediately on input unlike the numeric/text fields.
> 
makes sense
> > I would allow for return button to accept a new prop value. You can tab through the props which is nice and it would be great to allow you to tab, type to edit and then return to accept.
> 
> Done
> 
cool
> > looks like there is an assumption that the ancestor has to be a card, which is not the case for parts on a stack.
> > also this error is throw when i add a button and click on the editor halo-icon
> 
> These were actually the same bug, which I've now fixed
> 
> > that's not that useful. Maybe it should close the editor maybe it should center the script field. I also can't toggle the script editor which is what i expect within the editor itself
> 
> The Editor will now open the scriptEditor (at 100@100 now) and close itself. This is a better flow for sure.
> 
looks like the editor is not closing. This is after i click:
image
and since you don't see it you are liable to click again
image


i think there was a check on the old editor to make sure to only open the script field if it's not already there


> > I wonder if the best thing to do is simply edit the script in the messenger console?, i.e. there are two modes: send message to part and edit the script (but this is more work)
> 
> We discussed that and decided we wanted to keep the script editor as a pure Simpletalk composition, which I think is the right move. I too was tempted to add a basic script editor into the Editor panes but after our conversation decided against it.
ok

**Comment by darth-cheney** [comment]
Forgot to push changes. Those issues should now be resolved

**Pull request merged**
