### PR TITLE
Adding smart resizing to ContextMenu and any submenus

### PR DESCRIPTION
**Pull request by darth-cheney**
## What ##
This PR ensures that the ContextMenu and any "revealed" submenus will not
render outside of the bounds of the browser window view (ie, be
clipped and therefore only partially visible)
  
## Closes ##
Issue #88

### CODE REVIEW

**Comment by dkrasner** [comment]
@darth-cheney we definitely need this, i am still having some issues like:
image

in the above situation the context menu is completely hidden from view, unlike when the nav is open it just can be seen above it

**Comment by darth-cheney** [comment]
Just so I'm clear, you opened a context menu after opening the editor?
  
Either way I think I know what the issue is. The nav is in the outer DOM while the ContextMenu is inserted into the World (which is transformed when the editor is open). It might be that just moving the ContextMenu out into the upper DOM resolves this issue. I will test in a bit and see

**Comment by dkrasner** [comment]
yes i opened the context menu after the editor; this is a pretty common thing to do if you want to say close the halo when editing and do something with the part (move it, click the button) and see whatever props change in the editor itself (I use to 'debug' step handlers for example)

**Comment by darth-cheney** [comment]
Ok try it now. I think I've fixed it.

**Comment by dkrasner** [comment]
looks good to me @darth-cheney merge if you are ready

**Pull request merged**
